//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// График отпуск.
    /// </summary>
    // *** Start programmer edit section *** (ГрафикОтпуск CustomAttributes)

    // *** End programmer edit section *** (ГрафикОтпуск CustomAttributes)
    [AutoAltered()]
    [Caption("График отпуск")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГрафикОтпускE", new string[] {
            "ДатаДк as \'Дата дк\'",
            "Период as \'Период\'",
            "РуководительОр as \'Руководитель ор\'",
            "РуководительКО as \'Руководитель КО\'",
            "ОтделКадров as \'Отдел кадров\'"})]
    [MasterViewDefineAttribute("ГрафикОтпускE", "ОтделКадров", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [View("ГрафикОтпускL", new string[] {
            "ДатаДк as \'Дата дк\'",
            "Период as \'Период\'",
            "РуководительОр as \'Руководитель ор\'",
            "РуководительКО as \'Руководитель КО\'"})]
    public class ГрафикОтпуск : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаДк;
        
        private System.DateTime fПериод;
        
        private string fРуководительОр;
        
        private string fРуководительКО;
        
        private IIS.Otdel_kadrov_2.ОтделКадров fОтделКадров;
        
        // *** Start programmer edit section *** (ГрафикОтпуск CustomMembers)

        // *** End programmer edit section *** (ГрафикОтпуск CustomMembers)

        
        /// <summary>
        /// ДатаДк.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуск.ДатаДк CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуск.ДатаДк CustomAttributes)
        public virtual System.DateTime ДатаДк
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.ДатаДк Get start)

                // *** End programmer edit section *** (ГрафикОтпуск.ДатаДк Get start)
                System.DateTime result = this.fДатаДк;
                // *** Start programmer edit section *** (ГрафикОтпуск.ДатаДк Get end)

                // *** End programmer edit section *** (ГрафикОтпуск.ДатаДк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.ДатаДк Set start)

                // *** End programmer edit section *** (ГрафикОтпуск.ДатаДк Set start)
                this.fДатаДк = value;
                // *** Start programmer edit section *** (ГрафикОтпуск.ДатаДк Set end)

                // *** End programmer edit section *** (ГрафикОтпуск.ДатаДк Set end)
            }
        }
        
        /// <summary>
        /// Период.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуск.Период CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуск.Период CustomAttributes)
        public virtual System.DateTime Период
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.Период Get start)

                // *** End programmer edit section *** (ГрафикОтпуск.Период Get start)
                System.DateTime result = this.fПериод;
                // *** Start programmer edit section *** (ГрафикОтпуск.Период Get end)

                // *** End programmer edit section *** (ГрафикОтпуск.Период Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.Период Set start)

                // *** End programmer edit section *** (ГрафикОтпуск.Период Set start)
                this.fПериод = value;
                // *** Start programmer edit section *** (ГрафикОтпуск.Период Set end)

                // *** End programmer edit section *** (ГрафикОтпуск.Период Set end)
            }
        }
        
        /// <summary>
        /// РуководительКО.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуск.РуководительКО CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуск.РуководительКО CustomAttributes)
        [StrLen(255)]
        public virtual string РуководительКО
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.РуководительКО Get start)

                // *** End programmer edit section *** (ГрафикОтпуск.РуководительКО Get start)
                string result = this.fРуководительКО;
                // *** Start programmer edit section *** (ГрафикОтпуск.РуководительКО Get end)

                // *** End programmer edit section *** (ГрафикОтпуск.РуководительКО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.РуководительКО Set start)

                // *** End programmer edit section *** (ГрафикОтпуск.РуководительКО Set start)
                this.fРуководительКО = value;
                // *** Start programmer edit section *** (ГрафикОтпуск.РуководительКО Set end)

                // *** End programmer edit section *** (ГрафикОтпуск.РуководительКО Set end)
            }
        }
        
        /// <summary>
        /// РуководительОр.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуск.РуководительОр CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуск.РуководительОр CustomAttributes)
        [StrLen(255)]
        public virtual string РуководительОр
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.РуководительОр Get start)

                // *** End programmer edit section *** (ГрафикОтпуск.РуководительОр Get start)
                string result = this.fРуководительОр;
                // *** Start programmer edit section *** (ГрафикОтпуск.РуководительОр Get end)

                // *** End programmer edit section *** (ГрафикОтпуск.РуководительОр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.РуководительОр Set start)

                // *** End programmer edit section *** (ГрафикОтпуск.РуководительОр Set start)
                this.fРуководительОр = value;
                // *** Start programmer edit section *** (ГрафикОтпуск.РуководительОр Set end)

                // *** End programmer edit section *** (ГрафикОтпуск.РуководительОр Set end)
            }
        }
        
        /// <summary>
        /// График отпуск.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикОтпуск.ОтделКадров CustomAttributes)

        // *** End programmer edit section *** (ГрафикОтпуск.ОтделКадров CustomAttributes)
        [PropertyStorage(new string[] {
                "ОтделКадров"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov_2.ОтделКадров ОтделКадров
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.ОтделКадров Get start)

                // *** End programmer edit section *** (ГрафикОтпуск.ОтделКадров Get start)
                IIS.Otdel_kadrov_2.ОтделКадров result = this.fОтделКадров;
                // *** Start programmer edit section *** (ГрафикОтпуск.ОтделКадров Get end)

                // *** End programmer edit section *** (ГрафикОтпуск.ОтделКадров Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикОтпуск.ОтделКадров Set start)

                // *** End programmer edit section *** (ГрафикОтпуск.ОтделКадров Set start)
                this.fОтделКадров = value;
                // *** Start programmer edit section *** (ГрафикОтпуск.ОтделКадров Set end)

                // *** End programmer edit section *** (ГрафикОтпуск.ОтделКадров Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГрафикОтпускE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикОтпускE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикОтпускE", typeof(IIS.Otdel_kadrov_2.ГрафикОтпуск));
                }
            }
            
            /// <summary>
            /// "ГрафикОтпускL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикОтпускL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикОтпускL", typeof(IIS.Otdel_kadrov_2.ГрафикОтпуск));
                }
            }
        }
    }
}
