//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov_2
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Занятость.
    /// </summary>
    // *** Start programmer edit section *** (Занятость CustomAttributes)

    // *** End programmer edit section *** (Занятость CustomAttributes)
    public enum Занятость
    {
        
        // *** Start programmer edit section *** (Занятость.ВремНеполнаяЗан CustomAttributes)

        // *** End programmer edit section *** (Занятость.ВремНеполнаяЗан CustomAttributes)
        ВремНеполнаяЗан,
        
        // *** Start programmer edit section *** (Занятость.НеполнаяЗан CustomAttributes)

        // *** End programmer edit section *** (Занятость.НеполнаяЗан CustomAttributes)
        НеполнаяЗан,
        
        // *** Start programmer edit section *** (Занятость.УслованаяЗан CustomAttributes)

        // *** End programmer edit section *** (Занятость.УслованаяЗан CustomAttributes)
        УслованаяЗан,
        
        // *** Start programmer edit section *** (Занятость.НерегЗан CustomAttributes)

        // *** End programmer edit section *** (Занятость.НерегЗан CustomAttributes)
        НерегЗан,
        
        // *** Start programmer edit section *** (Занятость.ТеневаяЗан CustomAttributes)

        // *** End programmer edit section *** (Занятость.ТеневаяЗан CustomAttributes)
        ТеневаяЗан,
        
        // *** Start programmer edit section *** (Занятость.ВторичнаяЗан CustomAttributes)

        // *** End programmer edit section *** (Занятость.ВторичнаяЗан CustomAttributes)
        ВторичнаяЗан,
        
        // *** Start programmer edit section *** (Занятость.ПолстояннаяЗан CustomAttributes)

        // *** End programmer edit section *** (Занятость.ПолстояннаяЗан CustomAttributes)
        ПолстояннаяЗан,
        
        // *** Start programmer edit section *** (Занятость.ЧастичнаяЗан CustomAttributes)

        // *** End programmer edit section *** (Занятость.ЧастичнаяЗан CustomAttributes)
        ЧастичнаяЗан,
    }
}
