//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov_2
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Образование.
    /// </summary>
    // *** Start programmer edit section *** (Образование CustomAttributes)

    // *** End programmer edit section *** (Образование CustomAttributes)
    public enum Образование
    {
        
        // *** Start programmer edit section *** (Образование.Высшее1 CustomAttributes)

        // *** End programmer edit section *** (Образование.Высшее1 CustomAttributes)
        Высшее1,
        
        // *** Start programmer edit section *** (Образование.СреднееПроф CustomAttributes)

        // *** End programmer edit section *** (Образование.СреднееПроф CustomAttributes)
        СреднееПроф,
        
        // *** Start programmer edit section *** (Образование.Высшее2 CustomAttributes)

        // *** End programmer edit section *** (Образование.Высшее2 CustomAttributes)
        Высшее2,
        
        // *** Start programmer edit section *** (Образование.Высшее3 CustomAttributes)

        // *** End programmer edit section *** (Образование.Высшее3 CustomAttributes)
        Высшее3,
    }
}
