//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отдел кадров.
    /// </summary>
    // *** Start programmer edit section *** (ОтделКадров CustomAttributes)

    // *** End programmer edit section *** (ОтделКадров CustomAttributes)
    [AutoAltered()]
    [Caption("Отдел кадров")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтделКадровE", new string[] {
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("ОтделКадровE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОтделКадровL", new string[] {
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class ОтделКадров : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Otdel_kadrov_2.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ОтделКадров CustomMembers)

        // *** End programmer edit section *** (ОтделКадров CustomMembers)

        
        /// <summary>
        /// Отдел кадров.
        /// </summary>
        // *** Start programmer edit section *** (ОтделКадров.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОтделКадров.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov_2.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОтделКадров.Сотрудники Get start)

                // *** End programmer edit section *** (ОтделКадров.Сотрудники Get start)
                IIS.Otdel_kadrov_2.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОтделКадров.Сотрудники Get end)

                // *** End programmer edit section *** (ОтделКадров.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтделКадров.Сотрудники Set start)

                // *** End programmer edit section *** (ОтделКадров.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОтделКадров.Сотрудники Set end)

                // *** End programmer edit section *** (ОтделКадров.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтделКадровE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделКадровE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделКадровE", typeof(IIS.Otdel_kadrov_2.ОтделКадров));
                }
            }
            
            /// <summary>
            /// "ОтделКадровL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделКадровL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделКадровL", typeof(IIS.Otdel_kadrov_2.ОтделКадров));
                }
            }
        }
    }
}
