//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov_2
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Подразделение.
    /// </summary>
    // *** Start programmer edit section *** (Подразделение CustomAttributes)

    // *** End programmer edit section *** (Подразделение CustomAttributes)
    public enum Подразделение
    {
        
        // *** Start programmer edit section *** (Подразделение.ВалютныйОтдел CustomAttributes)

        // *** End programmer edit section *** (Подразделение.ВалютныйОтдел CustomAttributes)
        ВалютныйОтдел,
        
        // *** Start programmer edit section *** (Подразделение.ОтделКредит CustomAttributes)

        // *** End programmer edit section *** (Подразделение.ОтделКредит CustomAttributes)
        ОтделКредит,
        
        // *** Start programmer edit section *** (Подразделение.ОтделПлан CustomAttributes)

        // *** End programmer edit section *** (Подразделение.ОтделПлан CustomAttributes)
        ОтделПлан,
        
        // *** Start programmer edit section *** (Подразделение.ПлатежныйОт CustomAttributes)

        // *** End programmer edit section *** (Подразделение.ПлатежныйОт CustomAttributes)
        ПлатежныйОт,
        
        // *** Start programmer edit section *** (Подразделение.Бухгалтерия CustomAttributes)

        // *** End programmer edit section *** (Подразделение.Бухгалтерия CustomAttributes)
        Бухгалтерия,
        
        // *** Start programmer edit section *** (Подразделение.ИнвестОт CustomAttributes)

        // *** End programmer edit section *** (Подразделение.ИнвестОт CustomAttributes)
        ИнвестОт,
        
        // *** Start programmer edit section *** (Подразделение.ОтДепОпер CustomAttributes)

        // *** End programmer edit section *** (Подразделение.ОтДепОпер CustomAttributes)
        ОтДепОпер,
        
        // *** Start programmer edit section *** (Подразделение.ЮрОтедл CustomAttributes)

        // *** End programmer edit section *** (Подразделение.ЮрОтедл CustomAttributes)
        ЮрОтедл,
        
        // *** Start programmer edit section *** (Подразделение.ОтПоСтрах CustomAttributes)

        // *** End programmer edit section *** (Подразделение.ОтПоСтрах CustomAttributes)
        ОтПоСтрах,
        
        // *** Start programmer edit section *** (Подразделение.ОперацПодр CustomAttributes)

        // *** End programmer edit section *** (Подразделение.ОперацПодр CustomAttributes)
        ОперацПодр,
        
        // *** Start programmer edit section *** (Подразделение.ОтКадров CustomAttributes)

        // *** End programmer edit section *** (Подразделение.ОтКадров CustomAttributes)
        ОтКадров,
    }
}
