//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Приказ о приеме.
    /// </summary>
    // *** Start programmer edit section *** (ПриказОПриеме CustomAttributes)

    // *** End programmer edit section *** (ПриказОПриеме CustomAttributes)
    [AutoAltered()]
    [Caption("Приказ о приеме")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриказОПриемеE", new string[] {
            "Подразделение as \'Подразделение\'",
            "Оклад as \'Оклад\'",
            "ФИО as \'ФИО\'",
            "ГрафикРаботы as \'График работы\'",
            "ДатаДк as \'Дата дк\'",
            "Ответсвенный as \'Ответсвенный\'",
            "СрокЗаключения as \'Срок заключения\'",
            "ДатаПриема as \'Дата приема\'",
            "Занятость as \'Занятость\'",
            "Должность as \'Должность\'",
            "Должность.Наименование as \'Наименование\'",
            "ОтделКадров as \'Отдел кадров\'"}, Hidden=new string[] {
            "Должность.Наименование"})]
    [MasterViewDefineAttribute("ПриказОПриемеE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ПриказОПриемеE", "ОтделКадров", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [View("ПриказОПриемеL", new string[] {
            "ДатаДк as \'Дата дк\'",
            "Подразделение as \'Подразделение\'",
            "Оклад as \'Оклад\'",
            "ФИО as \'ФИО\'",
            "ГрафикРаботы as \'График работы\'",
            "Ответсвенный as \'Ответсвенный\'",
            "СрокЗаключения as \'Срок заключения\'",
            "ДатаПриема as \'Дата приема\'",
            "Занятость as \'Занятость\'",
            "Должность.Наименование as \'Наименование\'"})]
    public class ПриказОПриеме : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Otdel_kadrov_2.Подразделение fПодразделение;
        
        private double fОклад;
        
        private string fФИО;
        
        private string fГрафикРаботы;
        
        private System.DateTime fДатаДк;
        
        private string fОтветсвенный;
        
        private int fСрокЗаключения;
        
        private System.DateTime fДатаПриема;
        
        private IIS.Otdel_kadrov_2.Занятость fЗанятость;
        
        private IIS.Otdel_kadrov_2.Должность fДолжность;
        
        private IIS.Otdel_kadrov_2.ОтделКадров fОтделКадров;
        
        // *** Start programmer edit section *** (ПриказОПриеме CustomMembers)

        // *** End programmer edit section *** (ПриказОПриеме CustomMembers)

        
        /// <summary>
        /// ГрафикРаботы.
        /// </summary>
        // *** Start programmer edit section *** (ПриказОПриеме.ГрафикРаботы CustomAttributes)

        // *** End programmer edit section *** (ПриказОПриеме.ГрафикРаботы CustomAttributes)
        [StrLen(255)]
        public virtual string ГрафикРаботы
        {
            get
            {
                // *** Start programmer edit section *** (ПриказОПриеме.ГрафикРаботы Get start)

                // *** End programmer edit section *** (ПриказОПриеме.ГрафикРаботы Get start)
                string result = this.fГрафикРаботы;
                // *** Start programmer edit section *** (ПриказОПриеме.ГрафикРаботы Get end)

                // *** End programmer edit section *** (ПриказОПриеме.ГрафикРаботы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриказОПриеме.ГрафикРаботы Set start)

                // *** End programmer edit section *** (ПриказОПриеме.ГрафикРаботы Set start)
                this.fГрафикРаботы = value;
                // *** Start programmer edit section *** (ПриказОПриеме.ГрафикРаботы Set end)

                // *** End programmer edit section *** (ПриказОПриеме.ГрафикРаботы Set end)
            }
        }
        
        /// <summary>
        /// ДатаДк.
        /// </summary>
        // *** Start programmer edit section *** (ПриказОПриеме.ДатаДк CustomAttributes)

        // *** End programmer edit section *** (ПриказОПриеме.ДатаДк CustomAttributes)
        public virtual System.DateTime ДатаДк
        {
            get
            {
                // *** Start programmer edit section *** (ПриказОПриеме.ДатаДк Get start)

                // *** End programmer edit section *** (ПриказОПриеме.ДатаДк Get start)
                System.DateTime result = this.fДатаДк;
                // *** Start programmer edit section *** (ПриказОПриеме.ДатаДк Get end)

                // *** End programmer edit section *** (ПриказОПриеме.ДатаДк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриказОПриеме.ДатаДк Set start)

                // *** End programmer edit section *** (ПриказОПриеме.ДатаДк Set start)
                this.fДатаДк = value;
                // *** Start programmer edit section *** (ПриказОПриеме.ДатаДк Set end)

                // *** End programmer edit section *** (ПриказОПриеме.ДатаДк Set end)
            }
        }
        
        /// <summary>
        /// ДатаПриема.
        /// </summary>
        // *** Start programmer edit section *** (ПриказОПриеме.ДатаПриема CustomAttributes)

        // *** End programmer edit section *** (ПриказОПриеме.ДатаПриема CustomAttributes)
        public virtual System.DateTime ДатаПриема
        {
            get
            {
                // *** Start programmer edit section *** (ПриказОПриеме.ДатаПриема Get start)

                // *** End programmer edit section *** (ПриказОПриеме.ДатаПриема Get start)
                System.DateTime result = this.fДатаПриема;
                // *** Start programmer edit section *** (ПриказОПриеме.ДатаПриема Get end)

                // *** End programmer edit section *** (ПриказОПриеме.ДатаПриема Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриказОПриеме.ДатаПриема Set start)

                // *** End programmer edit section *** (ПриказОПриеме.ДатаПриема Set start)
                this.fДатаПриема = value;
                // *** Start programmer edit section *** (ПриказОПриеме.ДатаПриема Set end)

                // *** End programmer edit section *** (ПриказОПриеме.ДатаПриема Set end)
            }
        }
        
        /// <summary>
        /// Занятость.
        /// </summary>
        // *** Start programmer edit section *** (ПриказОПриеме.Занятость CustomAttributes)

        // *** End programmer edit section *** (ПриказОПриеме.Занятость CustomAttributes)
        public virtual IIS.Otdel_kadrov_2.Занятость Занятость
        {
            get
            {
                // *** Start programmer edit section *** (ПриказОПриеме.Занятость Get start)

                // *** End programmer edit section *** (ПриказОПриеме.Занятость Get start)
                IIS.Otdel_kadrov_2.Занятость result = this.fЗанятость;
                // *** Start programmer edit section *** (ПриказОПриеме.Занятость Get end)

                // *** End programmer edit section *** (ПриказОПриеме.Занятость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриказОПриеме.Занятость Set start)

                // *** End programmer edit section *** (ПриказОПриеме.Занятость Set start)
                this.fЗанятость = value;
                // *** Start programmer edit section *** (ПриказОПриеме.Занятость Set end)

                // *** End programmer edit section *** (ПриказОПриеме.Занятость Set end)
            }
        }
        
        /// <summary>
        /// Оклад.
        /// </summary>
        // *** Start programmer edit section *** (ПриказОПриеме.Оклад CustomAttributes)

        // *** End programmer edit section *** (ПриказОПриеме.Оклад CustomAttributes)
        public virtual double Оклад
        {
            get
            {
                // *** Start programmer edit section *** (ПриказОПриеме.Оклад Get start)

                // *** End programmer edit section *** (ПриказОПриеме.Оклад Get start)
                double result = this.fОклад;
                // *** Start programmer edit section *** (ПриказОПриеме.Оклад Get end)

                // *** End programmer edit section *** (ПриказОПриеме.Оклад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриказОПриеме.Оклад Set start)

                // *** End programmer edit section *** (ПриказОПриеме.Оклад Set start)
                this.fОклад = value;
                // *** Start programmer edit section *** (ПриказОПриеме.Оклад Set end)

                // *** End programmer edit section *** (ПриказОПриеме.Оклад Set end)
            }
        }
        
        /// <summary>
        /// Ответсвенный.
        /// </summary>
        // *** Start programmer edit section *** (ПриказОПриеме.Ответсвенный CustomAttributes)

        // *** End programmer edit section *** (ПриказОПриеме.Ответсвенный CustomAttributes)
        [StrLen(255)]
        public virtual string Ответсвенный
        {
            get
            {
                // *** Start programmer edit section *** (ПриказОПриеме.Ответсвенный Get start)

                // *** End programmer edit section *** (ПриказОПриеме.Ответсвенный Get start)
                string result = this.fОтветсвенный;
                // *** Start programmer edit section *** (ПриказОПриеме.Ответсвенный Get end)

                // *** End programmer edit section *** (ПриказОПриеме.Ответсвенный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриказОПриеме.Ответсвенный Set start)

                // *** End programmer edit section *** (ПриказОПриеме.Ответсвенный Set start)
                this.fОтветсвенный = value;
                // *** Start programmer edit section *** (ПриказОПриеме.Ответсвенный Set end)

                // *** End programmer edit section *** (ПриказОПриеме.Ответсвенный Set end)
            }
        }
        
        /// <summary>
        /// Подразделение.
        /// </summary>
        // *** Start programmer edit section *** (ПриказОПриеме.Подразделение CustomAttributes)

        // *** End programmer edit section *** (ПриказОПриеме.Подразделение CustomAttributes)
        public virtual IIS.Otdel_kadrov_2.Подразделение Подразделение
        {
            get
            {
                // *** Start programmer edit section *** (ПриказОПриеме.Подразделение Get start)

                // *** End programmer edit section *** (ПриказОПриеме.Подразделение Get start)
                IIS.Otdel_kadrov_2.Подразделение result = this.fПодразделение;
                // *** Start programmer edit section *** (ПриказОПриеме.Подразделение Get end)

                // *** End programmer edit section *** (ПриказОПриеме.Подразделение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриказОПриеме.Подразделение Set start)

                // *** End programmer edit section *** (ПриказОПриеме.Подразделение Set start)
                this.fПодразделение = value;
                // *** Start programmer edit section *** (ПриказОПриеме.Подразделение Set end)

                // *** End programmer edit section *** (ПриказОПриеме.Подразделение Set end)
            }
        }
        
        /// <summary>
        /// СрокЗаключения.
        /// </summary>
        // *** Start programmer edit section *** (ПриказОПриеме.СрокЗаключения CustomAttributes)

        // *** End programmer edit section *** (ПриказОПриеме.СрокЗаключения CustomAttributes)
        public virtual int СрокЗаключения
        {
            get
            {
                // *** Start programmer edit section *** (ПриказОПриеме.СрокЗаключения Get start)

                // *** End programmer edit section *** (ПриказОПриеме.СрокЗаключения Get start)
                int result = this.fСрокЗаключения;
                // *** Start programmer edit section *** (ПриказОПриеме.СрокЗаключения Get end)

                // *** End programmer edit section *** (ПриказОПриеме.СрокЗаключения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриказОПриеме.СрокЗаключения Set start)

                // *** End programmer edit section *** (ПриказОПриеме.СрокЗаключения Set start)
                this.fСрокЗаключения = value;
                // *** Start programmer edit section *** (ПриказОПриеме.СрокЗаключения Set end)

                // *** End programmer edit section *** (ПриказОПриеме.СрокЗаключения Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (ПриказОПриеме.ФИО CustomAttributes)

        // *** End programmer edit section *** (ПриказОПриеме.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (ПриказОПриеме.ФИО Get start)

                // *** End programmer edit section *** (ПриказОПриеме.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (ПриказОПриеме.ФИО Get end)

                // *** End programmer edit section *** (ПриказОПриеме.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриказОПриеме.ФИО Set start)

                // *** End programmer edit section *** (ПриказОПриеме.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (ПриказОПриеме.ФИО Set end)

                // *** End programmer edit section *** (ПриказОПриеме.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Приказ о приеме.
        /// </summary>
        // *** Start programmer edit section *** (ПриказОПриеме.Должность CustomAttributes)

        // *** End programmer edit section *** (ПриказОПриеме.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov_2.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (ПриказОПриеме.Должность Get start)

                // *** End programmer edit section *** (ПриказОПриеме.Должность Get start)
                IIS.Otdel_kadrov_2.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (ПриказОПриеме.Должность Get end)

                // *** End programmer edit section *** (ПриказОПриеме.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриказОПриеме.Должность Set start)

                // *** End programmer edit section *** (ПриказОПриеме.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (ПриказОПриеме.Должность Set end)

                // *** End programmer edit section *** (ПриказОПриеме.Должность Set end)
            }
        }
        
        /// <summary>
        /// Приказ о приеме.
        /// </summary>
        // *** Start programmer edit section *** (ПриказОПриеме.ОтделКадров CustomAttributes)

        // *** End programmer edit section *** (ПриказОПриеме.ОтделКадров CustomAttributes)
        [PropertyStorage(new string[] {
                "ОтделКадров"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov_2.ОтделКадров ОтделКадров
        {
            get
            {
                // *** Start programmer edit section *** (ПриказОПриеме.ОтделКадров Get start)

                // *** End programmer edit section *** (ПриказОПриеме.ОтделКадров Get start)
                IIS.Otdel_kadrov_2.ОтделКадров result = this.fОтделКадров;
                // *** Start programmer edit section *** (ПриказОПриеме.ОтделКадров Get end)

                // *** End programmer edit section *** (ПриказОПриеме.ОтделКадров Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриказОПриеме.ОтделКадров Set start)

                // *** End programmer edit section *** (ПриказОПриеме.ОтделКадров Set start)
                this.fОтделКадров = value;
                // *** Start programmer edit section *** (ПриказОПриеме.ОтделКадров Set end)

                // *** End programmer edit section *** (ПриказОПриеме.ОтделКадров Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриказОПриемеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриказОПриемеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриказОПриемеE", typeof(IIS.Otdel_kadrov_2.ПриказОПриеме));
                }
            }
            
            /// <summary>
            /// "ПриказОПриемеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриказОПриемеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриказОПриемеL", typeof(IIS.Otdel_kadrov_2.ПриказОПриеме));
                }
            }
        }
    }
}
