//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "ФИО as \'ФИО\'",
            "ДатаРождения as \'Дата рождения\'",
            "IDСотрудника as \'I d сотрудника\'",
            "Пол as \'Пол\'",
            "Подразделение as \'Подразделение\'",
            "ЗнаниеЯзыков as \'Знание языков\'",
            "Образование as \'Образование\'",
            "Гражданство as \'Гражданство\'",
            "Должность as \'Должность\'",
            "Должность.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Должность.Наименование"})]
    [MasterViewDefineAttribute("СотрудникиE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("СотрудникиL", new string[] {
            "ФИО as \'ФИО\'",
            "ДатаРождения as \'Дата рождения\'",
            "IDСотрудника as \'I d сотрудника\'",
            "Пол as \'Пол\'",
            "Подразделение as \'Подразделение\'",
            "ЗнаниеЯзыков as \'Знание языков\'",
            "Образование as \'Образование\'",
            "Гражданство as \'Гражданство\'",
            "Должность.Наименование as \'Наименование\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private System.DateTime fДатаРождения;
        
        private int fIDСотрудника;
        
        private string fПол;
        
        private IIS.Otdel_kadrov_2.Подразделение fПодразделение;
        
        private string fЗнаниеЯзыков;
        
        private IIS.Otdel_kadrov_2.Образование fОбразование;
        
        private string fГражданство;
        
        private IIS.Otdel_kadrov_2.Должность fДолжность;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// IDСотрудника.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.IDСотрудника CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.IDСотрудника CustomAttributes)
        public virtual int IDСотрудника
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.IDСотрудника Get start)

                // *** End programmer edit section *** (Сотрудники.IDСотрудника Get start)
                int result = this.fIDСотрудника;
                // *** Start programmer edit section *** (Сотрудники.IDСотрудника Get end)

                // *** End programmer edit section *** (Сотрудники.IDСотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.IDСотрудника Set start)

                // *** End programmer edit section *** (Сотрудники.IDСотрудника Set start)
                this.fIDСотрудника = value;
                // *** Start programmer edit section *** (Сотрудники.IDСотрудника Set end)

                // *** End programmer edit section *** (Сотрудники.IDСотрудника Set end)
            }
        }
        
        /// <summary>
        /// Гражданство.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Гражданство CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Гражданство CustomAttributes)
        [StrLen(255)]
        public virtual string Гражданство
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Гражданство Get start)

                // *** End programmer edit section *** (Сотрудники.Гражданство Get start)
                string result = this.fГражданство;
                // *** Start programmer edit section *** (Сотрудники.Гражданство Get end)

                // *** End programmer edit section *** (Сотрудники.Гражданство Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Гражданство Set start)

                // *** End programmer edit section *** (Сотрудники.Гражданство Set start)
                this.fГражданство = value;
                // *** Start programmer edit section *** (Сотрудники.Гражданство Set end)

                // *** End programmer edit section *** (Сотрудники.Гражданство Set end)
            }
        }
        
        /// <summary>
        /// ДатаРождения.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ДатаРождения CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ДатаРождения CustomAttributes)
        public virtual System.DateTime ДатаРождения
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ДатаРождения Get start)

                // *** End programmer edit section *** (Сотрудники.ДатаРождения Get start)
                System.DateTime result = this.fДатаРождения;
                // *** Start programmer edit section *** (Сотрудники.ДатаРождения Get end)

                // *** End programmer edit section *** (Сотрудники.ДатаРождения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ДатаРождения Set start)

                // *** End programmer edit section *** (Сотрудники.ДатаРождения Set start)
                this.fДатаРождения = value;
                // *** Start programmer edit section *** (Сотрудники.ДатаРождения Set end)

                // *** End programmer edit section *** (Сотрудники.ДатаРождения Set end)
            }
        }
        
        /// <summary>
        /// ЗнаниеЯзыков.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ЗнаниеЯзыков CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ЗнаниеЯзыков CustomAttributes)
        [StrLen(255)]
        public virtual string ЗнаниеЯзыков
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ЗнаниеЯзыков Get start)

                // *** End programmer edit section *** (Сотрудники.ЗнаниеЯзыков Get start)
                string result = this.fЗнаниеЯзыков;
                // *** Start programmer edit section *** (Сотрудники.ЗнаниеЯзыков Get end)

                // *** End programmer edit section *** (Сотрудники.ЗнаниеЯзыков Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ЗнаниеЯзыков Set start)

                // *** End programmer edit section *** (Сотрудники.ЗнаниеЯзыков Set start)
                this.fЗнаниеЯзыков = value;
                // *** Start programmer edit section *** (Сотрудники.ЗнаниеЯзыков Set end)

                // *** End programmer edit section *** (Сотрудники.ЗнаниеЯзыков Set end)
            }
        }
        
        /// <summary>
        /// Образование.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Образование CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Образование CustomAttributes)
        public virtual IIS.Otdel_kadrov_2.Образование Образование
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Образование Get start)

                // *** End programmer edit section *** (Сотрудники.Образование Get start)
                IIS.Otdel_kadrov_2.Образование result = this.fОбразование;
                // *** Start programmer edit section *** (Сотрудники.Образование Get end)

                // *** End programmer edit section *** (Сотрудники.Образование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Образование Set start)

                // *** End programmer edit section *** (Сотрудники.Образование Set start)
                this.fОбразование = value;
                // *** Start programmer edit section *** (Сотрудники.Образование Set end)

                // *** End programmer edit section *** (Сотрудники.Образование Set end)
            }
        }
        
        /// <summary>
        /// Подразделение.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Подразделение CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Подразделение CustomAttributes)
        public virtual IIS.Otdel_kadrov_2.Подразделение Подразделение
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Подразделение Get start)

                // *** End programmer edit section *** (Сотрудники.Подразделение Get start)
                IIS.Otdel_kadrov_2.Подразделение result = this.fПодразделение;
                // *** Start programmer edit section *** (Сотрудники.Подразделение Get end)

                // *** End programmer edit section *** (Сотрудники.Подразделение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Подразделение Set start)

                // *** End programmer edit section *** (Сотрудники.Подразделение Set start)
                this.fПодразделение = value;
                // *** Start programmer edit section *** (Сотрудники.Подразделение Set end)

                // *** End programmer edit section *** (Сотрудники.Подразделение Set end)
            }
        }
        
        /// <summary>
        /// Пол.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Пол CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Пол CustomAttributes)
        [StrLen(255)]
        public virtual string Пол
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Пол Get start)

                // *** End programmer edit section *** (Сотрудники.Пол Get start)
                string result = this.fПол;
                // *** Start programmer edit section *** (Сотрудники.Пол Get end)

                // *** End programmer edit section *** (Сотрудники.Пол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Пол Set start)

                // *** End programmer edit section *** (Сотрудники.Пол Set start)
                this.fПол = value;
                // *** Start programmer edit section *** (Сотрудники.Пол Set end)

                // *** End programmer edit section *** (Сотрудники.Пол Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ФИО CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ФИО Get start)

                // *** End programmer edit section *** (Сотрудники.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Сотрудники.ФИО Get end)

                // *** End programmer edit section *** (Сотрудники.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ФИО Set start)

                // *** End programmer edit section *** (Сотрудники.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Сотрудники.ФИО Set end)

                // *** End programmer edit section *** (Сотрудники.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Должность CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov_2.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Должность Get start)

                // *** End programmer edit section *** (Сотрудники.Должность Get start)
                IIS.Otdel_kadrov_2.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (Сотрудники.Должность Get end)

                // *** End programmer edit section *** (Сотрудники.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Должность Set start)

                // *** End programmer edit section *** (Сотрудники.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Сотрудники.Должность Set end)

                // *** End programmer edit section *** (Сотрудники.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.Otdel_kadrov_2.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.Otdel_kadrov_2.Сотрудники));
                }
            }
        }
    }
}
