//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сост штат рас.
    /// </summary>
    // *** Start programmer edit section *** (СостШтатРас CustomAttributes)

    // *** End programmer edit section *** (СостШтатРас CustomAttributes)
    [AutoAltered()]
    [Caption("Сост штат рас")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СостШтатРасE", new string[] {
            "Период as \'Период\'",
            "РуководительКО as \'Руководитель КО\'",
            "ДатаДк as \'Дата дк\'",
            "ГлавБух as \'Глав бух\'",
            "ОтделКадров as \'Отдел кадров\'"})]
    [MasterViewDefineAttribute("СостШтатРасE", "ОтделКадров", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [View("СостШтатРасL", new string[] {
            "Период as \'Период\'",
            "РуководительКО as \'Руководитель КО\'",
            "ДатаДк as \'Дата дк\'",
            "ГлавБух as \'Глав бух\'"})]
    public class СостШтатРас : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fПериод;
        
        private string fРуководительКО;
        
        private System.DateTime fДатаДк;
        
        private string fГлавБух;
        
        private IIS.Otdel_kadrov_2.ОтделКадров fОтделКадров;
        
        // *** Start programmer edit section *** (СостШтатРас CustomMembers)

        // *** End programmer edit section *** (СостШтатРас CustomMembers)

        
        /// <summary>
        /// ГлавБух.
        /// </summary>
        // *** Start programmer edit section *** (СостШтатРас.ГлавБух CustomAttributes)

        // *** End programmer edit section *** (СостШтатРас.ГлавБух CustomAttributes)
        [StrLen(255)]
        public virtual string ГлавБух
        {
            get
            {
                // *** Start programmer edit section *** (СостШтатРас.ГлавБух Get start)

                // *** End programmer edit section *** (СостШтатРас.ГлавБух Get start)
                string result = this.fГлавБух;
                // *** Start programmer edit section *** (СостШтатРас.ГлавБух Get end)

                // *** End programmer edit section *** (СостШтатРас.ГлавБух Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостШтатРас.ГлавБух Set start)

                // *** End programmer edit section *** (СостШтатРас.ГлавБух Set start)
                this.fГлавБух = value;
                // *** Start programmer edit section *** (СостШтатРас.ГлавБух Set end)

                // *** End programmer edit section *** (СостШтатРас.ГлавБух Set end)
            }
        }
        
        /// <summary>
        /// ДатаДк.
        /// </summary>
        // *** Start programmer edit section *** (СостШтатРас.ДатаДк CustomAttributes)

        // *** End programmer edit section *** (СостШтатРас.ДатаДк CustomAttributes)
        public virtual System.DateTime ДатаДк
        {
            get
            {
                // *** Start programmer edit section *** (СостШтатРас.ДатаДк Get start)

                // *** End programmer edit section *** (СостШтатРас.ДатаДк Get start)
                System.DateTime result = this.fДатаДк;
                // *** Start programmer edit section *** (СостШтатРас.ДатаДк Get end)

                // *** End programmer edit section *** (СостШтатРас.ДатаДк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостШтатРас.ДатаДк Set start)

                // *** End programmer edit section *** (СостШтатРас.ДатаДк Set start)
                this.fДатаДк = value;
                // *** Start programmer edit section *** (СостШтатРас.ДатаДк Set end)

                // *** End programmer edit section *** (СостШтатРас.ДатаДк Set end)
            }
        }
        
        /// <summary>
        /// Период.
        /// </summary>
        // *** Start programmer edit section *** (СостШтатРас.Период CustomAttributes)

        // *** End programmer edit section *** (СостШтатРас.Период CustomAttributes)
        public virtual System.DateTime Период
        {
            get
            {
                // *** Start programmer edit section *** (СостШтатРас.Период Get start)

                // *** End programmer edit section *** (СостШтатРас.Период Get start)
                System.DateTime result = this.fПериод;
                // *** Start programmer edit section *** (СостШтатРас.Период Get end)

                // *** End programmer edit section *** (СостШтатРас.Период Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостШтатРас.Период Set start)

                // *** End programmer edit section *** (СостШтатРас.Период Set start)
                this.fПериод = value;
                // *** Start programmer edit section *** (СостШтатРас.Период Set end)

                // *** End programmer edit section *** (СостШтатРас.Период Set end)
            }
        }
        
        /// <summary>
        /// РуководительКО.
        /// </summary>
        // *** Start programmer edit section *** (СостШтатРас.РуководительКО CustomAttributes)

        // *** End programmer edit section *** (СостШтатРас.РуководительКО CustomAttributes)
        [StrLen(255)]
        public virtual string РуководительКО
        {
            get
            {
                // *** Start programmer edit section *** (СостШтатРас.РуководительКО Get start)

                // *** End programmer edit section *** (СостШтатРас.РуководительКО Get start)
                string result = this.fРуководительКО;
                // *** Start programmer edit section *** (СостШтатРас.РуководительКО Get end)

                // *** End programmer edit section *** (СостШтатРас.РуководительКО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостШтатРас.РуководительКО Set start)

                // *** End programmer edit section *** (СостШтатРас.РуководительКО Set start)
                this.fРуководительКО = value;
                // *** Start programmer edit section *** (СостШтатРас.РуководительКО Set end)

                // *** End programmer edit section *** (СостШтатРас.РуководительКО Set end)
            }
        }
        
        /// <summary>
        /// Сост штат рас.
        /// </summary>
        // *** Start programmer edit section *** (СостШтатРас.ОтделКадров CustomAttributes)

        // *** End programmer edit section *** (СостШтатРас.ОтделКадров CustomAttributes)
        [PropertyStorage(new string[] {
                "ОтделКадров"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov_2.ОтделКадров ОтделКадров
        {
            get
            {
                // *** Start programmer edit section *** (СостШтатРас.ОтделКадров Get start)

                // *** End programmer edit section *** (СостШтатРас.ОтделКадров Get start)
                IIS.Otdel_kadrov_2.ОтделКадров result = this.fОтделКадров;
                // *** Start programmer edit section *** (СостШтатРас.ОтделКадров Get end)

                // *** End programmer edit section *** (СостШтатРас.ОтделКадров Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СостШтатРас.ОтделКадров Set start)

                // *** End programmer edit section *** (СостШтатРас.ОтделКадров Set start)
                this.fОтделКадров = value;
                // *** Start programmer edit section *** (СостШтатРас.ОтделКадров Set end)

                // *** End programmer edit section *** (СостШтатРас.ОтделКадров Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СостШтатРасE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СостШтатРасE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СостШтатРасE", typeof(IIS.Otdel_kadrov_2.СостШтатРас));
                }
            }
            
            /// <summary>
            /// "СостШтатРасL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СостШтатРасL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СостШтатРасL", typeof(IIS.Otdel_kadrov_2.СостШтатРас));
                }
            }
        }
    }
}
