//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Таб уч РВ.
    /// </summary>
    // *** Start programmer edit section *** (ТабУчРВ CustomAttributes)

    // *** End programmer edit section *** (ТабУчРВ CustomAttributes)
    [AutoAltered()]
    [Caption("Таб уч РВ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТабУчРВE", new string[] {
            "ДатаДк as \'Дата дк\'",
            "Руководитель as \'Руководитель\'",
            "Период as \'Период\'",
            "Исполнитель as \'Исполнитель\'",
            "ОтделКадров as \'Отдел кадров\'"})]
    [MasterViewDefineAttribute("ТабУчРВE", "ОтделКадров", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [View("ТабУчРВL", new string[] {
            "ДатаДк as \'Дата дк\'",
            "Руководитель as \'Руководитель\'",
            "Период as \'Период\'",
            "Исполнитель as \'Исполнитель\'"})]
    public class ТабУчРВ : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаДк;
        
        private string fРуководитель;
        
        private System.DateTime fПериод;
        
        private string fИсполнитель;
        
        private IIS.Otdel_kadrov_2.ОтделКадров fОтделКадров;
        
        // *** Start programmer edit section *** (ТабУчРВ CustomMembers)

        // *** End programmer edit section *** (ТабУчРВ CustomMembers)

        
        /// <summary>
        /// ДатаДк.
        /// </summary>
        // *** Start programmer edit section *** (ТабУчРВ.ДатаДк CustomAttributes)

        // *** End programmer edit section *** (ТабУчРВ.ДатаДк CustomAttributes)
        public virtual System.DateTime ДатаДк
        {
            get
            {
                // *** Start programmer edit section *** (ТабУчРВ.ДатаДк Get start)

                // *** End programmer edit section *** (ТабУчРВ.ДатаДк Get start)
                System.DateTime result = this.fДатаДк;
                // *** Start programmer edit section *** (ТабУчРВ.ДатаДк Get end)

                // *** End programmer edit section *** (ТабУчРВ.ДатаДк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТабУчРВ.ДатаДк Set start)

                // *** End programmer edit section *** (ТабУчРВ.ДатаДк Set start)
                this.fДатаДк = value;
                // *** Start programmer edit section *** (ТабУчРВ.ДатаДк Set end)

                // *** End programmer edit section *** (ТабУчРВ.ДатаДк Set end)
            }
        }
        
        /// <summary>
        /// Исполнитель.
        /// </summary>
        // *** Start programmer edit section *** (ТабУчРВ.Исполнитель CustomAttributes)

        // *** End programmer edit section *** (ТабУчРВ.Исполнитель CustomAttributes)
        [StrLen(255)]
        public virtual string Исполнитель
        {
            get
            {
                // *** Start programmer edit section *** (ТабУчРВ.Исполнитель Get start)

                // *** End programmer edit section *** (ТабУчРВ.Исполнитель Get start)
                string result = this.fИсполнитель;
                // *** Start programmer edit section *** (ТабУчРВ.Исполнитель Get end)

                // *** End programmer edit section *** (ТабУчРВ.Исполнитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТабУчРВ.Исполнитель Set start)

                // *** End programmer edit section *** (ТабУчРВ.Исполнитель Set start)
                this.fИсполнитель = value;
                // *** Start programmer edit section *** (ТабУчРВ.Исполнитель Set end)

                // *** End programmer edit section *** (ТабУчРВ.Исполнитель Set end)
            }
        }
        
        /// <summary>
        /// Период.
        /// </summary>
        // *** Start programmer edit section *** (ТабУчРВ.Период CustomAttributes)

        // *** End programmer edit section *** (ТабУчРВ.Период CustomAttributes)
        public virtual System.DateTime Период
        {
            get
            {
                // *** Start programmer edit section *** (ТабУчРВ.Период Get start)

                // *** End programmer edit section *** (ТабУчРВ.Период Get start)
                System.DateTime result = this.fПериод;
                // *** Start programmer edit section *** (ТабУчРВ.Период Get end)

                // *** End programmer edit section *** (ТабУчРВ.Период Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТабУчРВ.Период Set start)

                // *** End programmer edit section *** (ТабУчРВ.Период Set start)
                this.fПериод = value;
                // *** Start programmer edit section *** (ТабУчРВ.Период Set end)

                // *** End programmer edit section *** (ТабУчРВ.Период Set end)
            }
        }
        
        /// <summary>
        /// Руководитель.
        /// </summary>
        // *** Start programmer edit section *** (ТабУчРВ.Руководитель CustomAttributes)

        // *** End programmer edit section *** (ТабУчРВ.Руководитель CustomAttributes)
        [StrLen(255)]
        public virtual string Руководитель
        {
            get
            {
                // *** Start programmer edit section *** (ТабУчРВ.Руководитель Get start)

                // *** End programmer edit section *** (ТабУчРВ.Руководитель Get start)
                string result = this.fРуководитель;
                // *** Start programmer edit section *** (ТабУчРВ.Руководитель Get end)

                // *** End programmer edit section *** (ТабУчРВ.Руководитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТабУчРВ.Руководитель Set start)

                // *** End programmer edit section *** (ТабУчРВ.Руководитель Set start)
                this.fРуководитель = value;
                // *** Start programmer edit section *** (ТабУчРВ.Руководитель Set end)

                // *** End programmer edit section *** (ТабУчРВ.Руководитель Set end)
            }
        }
        
        /// <summary>
        /// Таб уч РВ.
        /// </summary>
        // *** Start programmer edit section *** (ТабУчРВ.ОтделКадров CustomAttributes)

        // *** End programmer edit section *** (ТабУчРВ.ОтделКадров CustomAttributes)
        [PropertyStorage(new string[] {
                "ОтделКадров"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov_2.ОтделКадров ОтделКадров
        {
            get
            {
                // *** Start programmer edit section *** (ТабУчРВ.ОтделКадров Get start)

                // *** End programmer edit section *** (ТабУчРВ.ОтделКадров Get start)
                IIS.Otdel_kadrov_2.ОтделКадров result = this.fОтделКадров;
                // *** Start programmer edit section *** (ТабУчРВ.ОтделКадров Get end)

                // *** End programmer edit section *** (ТабУчРВ.ОтделКадров Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТабУчРВ.ОтделКадров Set start)

                // *** End programmer edit section *** (ТабУчРВ.ОтделКадров Set start)
                this.fОтделКадров = value;
                // *** Start programmer edit section *** (ТабУчРВ.ОтделКадров Set end)

                // *** End programmer edit section *** (ТабУчРВ.ОтделКадров Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТабУчРВE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТабУчРВE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТабУчРВE", typeof(IIS.Otdel_kadrov_2.ТабУчРВ));
                }
            }
            
            /// <summary>
            /// "ТабУчРВL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТабУчРВL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТабУчРВL", typeof(IIS.Otdel_kadrov_2.ТабУчРВ));
                }
            }
        }
    }
}
