//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Табл часть ГО.
    /// </summary>
    // *** Start programmer edit section *** (ТаблЧастьГО CustomAttributes)

    // *** End programmer edit section *** (ТаблЧастьГО CustomAttributes)
    [AutoAltered()]
    [Caption("Табл часть ГО")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТаблЧастьГОE", new string[] {
            "Код as \'Код\'",
            "КолКалДней as \'Кол кал дней\'",
            "ДатаЗап as \'Дата зап\'",
            "ДатаФакт as \'Дата факт\'",
            "Основание as \'Основание\'",
            "Перенос as \'Перенос\'",
            "Примечание as \'Примечание\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("ТаблЧастьГОE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ТаблЧастьГОL", new string[] {
            "Код as \'Код\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "КолКалДней as \'Кол кал дней\'",
            "ДатаЗап as \'Дата зап\'",
            "ДатаФакт as \'Дата факт\'",
            "Основание as \'Основание\'",
            "Перенос as \'Перенос\'",
            "Примечание as \'Примечание\'"})]
    public class ТаблЧастьГО : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private int fКолКалДней;
        
        private System.DateTime fДатаЗап;
        
        private System.DateTime fДатаФакт;
        
        private string fОснование;
        
        private System.DateTime fПеренос;
        
        private string fПримечание;
        
        private IIS.Otdel_kadrov_2.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ТаблЧастьГО CustomMembers)

        // *** End programmer edit section *** (ТаблЧастьГО CustomMembers)

        
        /// <summary>
        /// ДатаЗап.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьГО.ДатаЗап CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьГО.ДатаЗап CustomAttributes)
        public virtual System.DateTime ДатаЗап
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.ДатаЗап Get start)

                // *** End programmer edit section *** (ТаблЧастьГО.ДатаЗап Get start)
                System.DateTime result = this.fДатаЗап;
                // *** Start programmer edit section *** (ТаблЧастьГО.ДатаЗап Get end)

                // *** End programmer edit section *** (ТаблЧастьГО.ДатаЗап Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.ДатаЗап Set start)

                // *** End programmer edit section *** (ТаблЧастьГО.ДатаЗап Set start)
                this.fДатаЗап = value;
                // *** Start programmer edit section *** (ТаблЧастьГО.ДатаЗап Set end)

                // *** End programmer edit section *** (ТаблЧастьГО.ДатаЗап Set end)
            }
        }
        
        /// <summary>
        /// ДатаФакт.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьГО.ДатаФакт CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьГО.ДатаФакт CustomAttributes)
        public virtual System.DateTime ДатаФакт
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.ДатаФакт Get start)

                // *** End programmer edit section *** (ТаблЧастьГО.ДатаФакт Get start)
                System.DateTime result = this.fДатаФакт;
                // *** Start programmer edit section *** (ТаблЧастьГО.ДатаФакт Get end)

                // *** End programmer edit section *** (ТаблЧастьГО.ДатаФакт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.ДатаФакт Set start)

                // *** End programmer edit section *** (ТаблЧастьГО.ДатаФакт Set start)
                this.fДатаФакт = value;
                // *** Start programmer edit section *** (ТаблЧастьГО.ДатаФакт Set end)

                // *** End programmer edit section *** (ТаблЧастьГО.ДатаФакт Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьГО.Код CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьГО.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.Код Get start)

                // *** End programmer edit section *** (ТаблЧастьГО.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (ТаблЧастьГО.Код Get end)

                // *** End programmer edit section *** (ТаблЧастьГО.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.Код Set start)

                // *** End programmer edit section *** (ТаблЧастьГО.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (ТаблЧастьГО.Код Set end)

                // *** End programmer edit section *** (ТаблЧастьГО.Код Set end)
            }
        }
        
        /// <summary>
        /// КолКалДней.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьГО.КолКалДней CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьГО.КолКалДней CustomAttributes)
        public virtual int КолКалДней
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.КолКалДней Get start)

                // *** End programmer edit section *** (ТаблЧастьГО.КолКалДней Get start)
                int result = this.fКолКалДней;
                // *** Start programmer edit section *** (ТаблЧастьГО.КолКалДней Get end)

                // *** End programmer edit section *** (ТаблЧастьГО.КолКалДней Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.КолКалДней Set start)

                // *** End programmer edit section *** (ТаблЧастьГО.КолКалДней Set start)
                this.fКолКалДней = value;
                // *** Start programmer edit section *** (ТаблЧастьГО.КолКалДней Set end)

                // *** End programmer edit section *** (ТаблЧастьГО.КолКалДней Set end)
            }
        }
        
        /// <summary>
        /// Основание.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьГО.Основание CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьГО.Основание CustomAttributes)
        [StrLen(255)]
        public virtual string Основание
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.Основание Get start)

                // *** End programmer edit section *** (ТаблЧастьГО.Основание Get start)
                string result = this.fОснование;
                // *** Start programmer edit section *** (ТаблЧастьГО.Основание Get end)

                // *** End programmer edit section *** (ТаблЧастьГО.Основание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.Основание Set start)

                // *** End programmer edit section *** (ТаблЧастьГО.Основание Set start)
                this.fОснование = value;
                // *** Start programmer edit section *** (ТаблЧастьГО.Основание Set end)

                // *** End programmer edit section *** (ТаблЧастьГО.Основание Set end)
            }
        }
        
        /// <summary>
        /// Перенос.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьГО.Перенос CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьГО.Перенос CustomAttributes)
        public virtual System.DateTime Перенос
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.Перенос Get start)

                // *** End programmer edit section *** (ТаблЧастьГО.Перенос Get start)
                System.DateTime result = this.fПеренос;
                // *** Start programmer edit section *** (ТаблЧастьГО.Перенос Get end)

                // *** End programmer edit section *** (ТаблЧастьГО.Перенос Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.Перенос Set start)

                // *** End programmer edit section *** (ТаблЧастьГО.Перенос Set start)
                this.fПеренос = value;
                // *** Start programmer edit section *** (ТаблЧастьГО.Перенос Set end)

                // *** End programmer edit section *** (ТаблЧастьГО.Перенос Set end)
            }
        }
        
        /// <summary>
        /// Примечание.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьГО.Примечание CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьГО.Примечание CustomAttributes)
        [StrLen(255)]
        public virtual string Примечание
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.Примечание Get start)

                // *** End programmer edit section *** (ТаблЧастьГО.Примечание Get start)
                string result = this.fПримечание;
                // *** Start programmer edit section *** (ТаблЧастьГО.Примечание Get end)

                // *** End programmer edit section *** (ТаблЧастьГО.Примечание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.Примечание Set start)

                // *** End programmer edit section *** (ТаблЧастьГО.Примечание Set start)
                this.fПримечание = value;
                // *** Start programmer edit section *** (ТаблЧастьГО.Примечание Set end)

                // *** End programmer edit section *** (ТаблЧастьГО.Примечание Set end)
            }
        }
        
        /// <summary>
        /// Табл часть ГО.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьГО.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьГО.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov_2.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.Сотрудники Get start)

                // *** End programmer edit section *** (ТаблЧастьГО.Сотрудники Get start)
                IIS.Otdel_kadrov_2.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ТаблЧастьГО.Сотрудники Get end)

                // *** End programmer edit section *** (ТаблЧастьГО.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьГО.Сотрудники Set start)

                // *** End programmer edit section *** (ТаблЧастьГО.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ТаблЧастьГО.Сотрудники Set end)

                // *** End programmer edit section *** (ТаблЧастьГО.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТаблЧастьГОE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТаблЧастьГОE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТаблЧастьГОE", typeof(IIS.Otdel_kadrov_2.ТаблЧастьГО));
                }
            }
            
            /// <summary>
            /// "ТаблЧастьГОL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТаблЧастьГОL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТаблЧастьГОL", typeof(IIS.Otdel_kadrov_2.ТаблЧастьГО));
                }
            }
        }
    }
}
