//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Табл часть сотруд.
    /// </summary>
    // *** Start programmer edit section *** (ТаблЧастьСотруд CustomAttributes)

    // *** End programmer edit section *** (ТаблЧастьСотруд CustomAttributes)
    [AutoAltered()]
    [Caption("Табл часть сотруд")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТаблЧастьСотрудE", new string[] {
            "НаимОбуч as \'Наим обуч\'",
            "Квалификация as \'Квалификация\'",
            "НаимДок as \'Наим док\'",
            "Cерия as \'Cерия\'",
            "Номер as \'Номер\'",
            "ГодОкончания as \'Год окончания\'"})]
    [View("ТаблЧастьСотрудL", new string[] {
            "НаимОбуч as \'Наим обуч\'",
            "Квалификация as \'Квалификация\'",
            "НаимДок as \'Наим док\'",
            "Cерия as \'Cерия\'",
            "Номер as \'Номер\'",
            "ГодОкончания as \'Год окончания\'"})]
    public class ТаблЧастьСотруд : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаимОбуч;
        
        private string fКвалификация;
        
        private string fНаимДок;
        
        private int fCерия;
        
        private int fНомер;
        
        private System.DateTime fГодОкончания;
        
        // *** Start programmer edit section *** (ТаблЧастьСотруд CustomMembers)

        // *** End programmer edit section *** (ТаблЧастьСотруд CustomMembers)

        
        /// <summary>
        /// Cерия.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьСотруд.Cерия CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьСотруд.Cерия CustomAttributes)
        public virtual int Cерия
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьСотруд.Cерия Get start)

                // *** End programmer edit section *** (ТаблЧастьСотруд.Cерия Get start)
                int result = this.fCерия;
                // *** Start programmer edit section *** (ТаблЧастьСотруд.Cерия Get end)

                // *** End programmer edit section *** (ТаблЧастьСотруд.Cерия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьСотруд.Cерия Set start)

                // *** End programmer edit section *** (ТаблЧастьСотруд.Cерия Set start)
                this.fCерия = value;
                // *** Start programmer edit section *** (ТаблЧастьСотруд.Cерия Set end)

                // *** End programmer edit section *** (ТаблЧастьСотруд.Cерия Set end)
            }
        }
        
        /// <summary>
        /// ГодОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьСотруд.ГодОкончания CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьСотруд.ГодОкончания CustomAttributes)
        public virtual System.DateTime ГодОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьСотруд.ГодОкончания Get start)

                // *** End programmer edit section *** (ТаблЧастьСотруд.ГодОкончания Get start)
                System.DateTime result = this.fГодОкончания;
                // *** Start programmer edit section *** (ТаблЧастьСотруд.ГодОкончания Get end)

                // *** End programmer edit section *** (ТаблЧастьСотруд.ГодОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьСотруд.ГодОкончания Set start)

                // *** End programmer edit section *** (ТаблЧастьСотруд.ГодОкончания Set start)
                this.fГодОкончания = value;
                // *** Start programmer edit section *** (ТаблЧастьСотруд.ГодОкончания Set end)

                // *** End programmer edit section *** (ТаблЧастьСотруд.ГодОкончания Set end)
            }
        }
        
        /// <summary>
        /// Квалификация.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьСотруд.Квалификация CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьСотруд.Квалификация CustomAttributes)
        [StrLen(255)]
        public virtual string Квалификация
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьСотруд.Квалификация Get start)

                // *** End programmer edit section *** (ТаблЧастьСотруд.Квалификация Get start)
                string result = this.fКвалификация;
                // *** Start programmer edit section *** (ТаблЧастьСотруд.Квалификация Get end)

                // *** End programmer edit section *** (ТаблЧастьСотруд.Квалификация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьСотруд.Квалификация Set start)

                // *** End programmer edit section *** (ТаблЧастьСотруд.Квалификация Set start)
                this.fКвалификация = value;
                // *** Start programmer edit section *** (ТаблЧастьСотруд.Квалификация Set end)

                // *** End programmer edit section *** (ТаблЧастьСотруд.Квалификация Set end)
            }
        }
        
        /// <summary>
        /// НаимДок.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьСотруд.НаимДок CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьСотруд.НаимДок CustomAttributes)
        [StrLen(255)]
        public virtual string НаимДок
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьСотруд.НаимДок Get start)

                // *** End programmer edit section *** (ТаблЧастьСотруд.НаимДок Get start)
                string result = this.fНаимДок;
                // *** Start programmer edit section *** (ТаблЧастьСотруд.НаимДок Get end)

                // *** End programmer edit section *** (ТаблЧастьСотруд.НаимДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьСотруд.НаимДок Set start)

                // *** End programmer edit section *** (ТаблЧастьСотруд.НаимДок Set start)
                this.fНаимДок = value;
                // *** Start programmer edit section *** (ТаблЧастьСотруд.НаимДок Set end)

                // *** End programmer edit section *** (ТаблЧастьСотруд.НаимДок Set end)
            }
        }
        
        /// <summary>
        /// НаимОбуч.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьСотруд.НаимОбуч CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьСотруд.НаимОбуч CustomAttributes)
        [StrLen(255)]
        public virtual string НаимОбуч
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьСотруд.НаимОбуч Get start)

                // *** End programmer edit section *** (ТаблЧастьСотруд.НаимОбуч Get start)
                string result = this.fНаимОбуч;
                // *** Start programmer edit section *** (ТаблЧастьСотруд.НаимОбуч Get end)

                // *** End programmer edit section *** (ТаблЧастьСотруд.НаимОбуч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьСотруд.НаимОбуч Set start)

                // *** End programmer edit section *** (ТаблЧастьСотруд.НаимОбуч Set start)
                this.fНаимОбуч = value;
                // *** Start programmer edit section *** (ТаблЧастьСотруд.НаимОбуч Set end)

                // *** End programmer edit section *** (ТаблЧастьСотруд.НаимОбуч Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьСотруд.Номер CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьСотруд.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьСотруд.Номер Get start)

                // *** End programmer edit section *** (ТаблЧастьСотруд.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ТаблЧастьСотруд.Номер Get end)

                // *** End programmer edit section *** (ТаблЧастьСотруд.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьСотруд.Номер Set start)

                // *** End programmer edit section *** (ТаблЧастьСотруд.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ТаблЧастьСотруд.Номер Set end)

                // *** End programmer edit section *** (ТаблЧастьСотруд.Номер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТаблЧастьСотрудE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТаблЧастьСотрудE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТаблЧастьСотрудE", typeof(IIS.Otdel_kadrov_2.ТаблЧастьСотруд));
                }
            }
            
            /// <summary>
            /// "ТаблЧастьСотрудL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТаблЧастьСотрудL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТаблЧастьСотрудL", typeof(IIS.Otdel_kadrov_2.ТаблЧастьСотруд));
                }
            }
        }
    }
}
