//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Табл часть ТУ.
    /// </summary>
    // *** Start programmer edit section *** (ТаблЧастьТУ CustomAttributes)

    // *** End programmer edit section *** (ТаблЧастьТУ CustomAttributes)
    [AutoAltered()]
    [Caption("Табл часть ТУ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТаблЧастьТУE", new string[] {
            "Код as \'Код\'",
            "ДатаДк as \'Дата дк\'",
            "ЯвкаНеявка as \'Явка неявка\'",
            "КолЯвокПМес as \'Кол явок п мес\'",
            "КолЯвокМес as \'Кол явок мес\'",
            "ЧасыЗаПМес as \'Часы за п мес\'",
            "ЧасыЗаМесяц as \'Часы за месяц\'",
            "КодВидаОплаты as \'Код вида оплаты\'",
            "КорресСчет as \'Коррес счет\'",
            "ДниЧасы as \'Дни часы\'",
            "КолНеявок as \'Кол неявок\'",
            "ИзНихПоПричинам as \'Из них по причинам\'",
            "КолВыхПразд as \'Кол вых празд\'"})]
    [View("ТаблЧастьТУL", new string[] {
            "Код as \'Код\'",
            "ДатаДк as \'Дата дк\'",
            "ЯвкаНеявка as \'Явка неявка\'",
            "КолЯвокПМес as \'Кол явок п мес\'",
            "КолЯвокМес as \'Кол явок мес\'",
            "ЧасыЗаПМес as \'Часы за п мес\'",
            "ЧасыЗаМесяц as \'Часы за месяц\'",
            "КодВидаОплаты as \'Код вида оплаты\'",
            "КорресСчет as \'Коррес счет\'",
            "ДниЧасы as \'Дни часы\'",
            "КолНеявок as \'Кол неявок\'",
            "ИзНихПоПричинам as \'Из них по причинам\'",
            "КолВыхПразд as \'Кол вых празд\'"})]
    public class ТаблЧастьТУ : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private System.DateTime fДатаДк;
        
        private bool fЯвкаНеявка;
        
        private int fКолЯвокПМес;
        
        private int fКолЯвокМес;
        
        private double fЧасыЗаПМес;
        
        private double fЧасыЗаМесяц;
        
        private string fКодВидаОплаты;
        
        private int fКорресСчет;
        
        private int fДниЧасы;
        
        private int fКолНеявок;
        
        private int fИзНихПоПричинам;
        
        private int fКолВыхПразд;
        
        // *** Start programmer edit section *** (ТаблЧастьТУ CustomMembers)

        // *** End programmer edit section *** (ТаблЧастьТУ CustomMembers)

        
        /// <summary>
        /// ДатаДк.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьТУ.ДатаДк CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьТУ.ДатаДк CustomAttributes)
        public virtual System.DateTime ДатаДк
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.ДатаДк Get start)

                // *** End programmer edit section *** (ТаблЧастьТУ.ДатаДк Get start)
                System.DateTime result = this.fДатаДк;
                // *** Start programmer edit section *** (ТаблЧастьТУ.ДатаДк Get end)

                // *** End programmer edit section *** (ТаблЧастьТУ.ДатаДк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.ДатаДк Set start)

                // *** End programmer edit section *** (ТаблЧастьТУ.ДатаДк Set start)
                this.fДатаДк = value;
                // *** Start programmer edit section *** (ТаблЧастьТУ.ДатаДк Set end)

                // *** End programmer edit section *** (ТаблЧастьТУ.ДатаДк Set end)
            }
        }
        
        /// <summary>
        /// ДниЧасы.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьТУ.ДниЧасы CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьТУ.ДниЧасы CustomAttributes)
        public virtual int ДниЧасы
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.ДниЧасы Get start)

                // *** End programmer edit section *** (ТаблЧастьТУ.ДниЧасы Get start)
                int result = this.fДниЧасы;
                // *** Start programmer edit section *** (ТаблЧастьТУ.ДниЧасы Get end)

                // *** End programmer edit section *** (ТаблЧастьТУ.ДниЧасы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.ДниЧасы Set start)

                // *** End programmer edit section *** (ТаблЧастьТУ.ДниЧасы Set start)
                this.fДниЧасы = value;
                // *** Start programmer edit section *** (ТаблЧастьТУ.ДниЧасы Set end)

                // *** End programmer edit section *** (ТаблЧастьТУ.ДниЧасы Set end)
            }
        }
        
        /// <summary>
        /// ИзНихПоПричинам.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьТУ.ИзНихПоПричинам CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьТУ.ИзНихПоПричинам CustomAttributes)
        public virtual int ИзНихПоПричинам
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.ИзНихПоПричинам Get start)

                // *** End programmer edit section *** (ТаблЧастьТУ.ИзНихПоПричинам Get start)
                int result = this.fИзНихПоПричинам;
                // *** Start programmer edit section *** (ТаблЧастьТУ.ИзНихПоПричинам Get end)

                // *** End programmer edit section *** (ТаблЧастьТУ.ИзНихПоПричинам Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.ИзНихПоПричинам Set start)

                // *** End programmer edit section *** (ТаблЧастьТУ.ИзНихПоПричинам Set start)
                this.fИзНихПоПричинам = value;
                // *** Start programmer edit section *** (ТаблЧастьТУ.ИзНихПоПричинам Set end)

                // *** End programmer edit section *** (ТаблЧастьТУ.ИзНихПоПричинам Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьТУ.Код CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьТУ.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.Код Get start)

                // *** End programmer edit section *** (ТаблЧастьТУ.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (ТаблЧастьТУ.Код Get end)

                // *** End programmer edit section *** (ТаблЧастьТУ.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.Код Set start)

                // *** End programmer edit section *** (ТаблЧастьТУ.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (ТаблЧастьТУ.Код Set end)

                // *** End programmer edit section *** (ТаблЧастьТУ.Код Set end)
            }
        }
        
        /// <summary>
        /// КодВидаОплаты.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьТУ.КодВидаОплаты CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьТУ.КодВидаОплаты CustomAttributes)
        [StrLen(255)]
        public virtual string КодВидаОплаты
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.КодВидаОплаты Get start)

                // *** End programmer edit section *** (ТаблЧастьТУ.КодВидаОплаты Get start)
                string result = this.fКодВидаОплаты;
                // *** Start programmer edit section *** (ТаблЧастьТУ.КодВидаОплаты Get end)

                // *** End programmer edit section *** (ТаблЧастьТУ.КодВидаОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.КодВидаОплаты Set start)

                // *** End programmer edit section *** (ТаблЧастьТУ.КодВидаОплаты Set start)
                this.fКодВидаОплаты = value;
                // *** Start programmer edit section *** (ТаблЧастьТУ.КодВидаОплаты Set end)

                // *** End programmer edit section *** (ТаблЧастьТУ.КодВидаОплаты Set end)
            }
        }
        
        /// <summary>
        /// КолВыхПразд.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьТУ.КолВыхПразд CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьТУ.КолВыхПразд CustomAttributes)
        public virtual int КолВыхПразд
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолВыхПразд Get start)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолВыхПразд Get start)
                int result = this.fКолВыхПразд;
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолВыхПразд Get end)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолВыхПразд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолВыхПразд Set start)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолВыхПразд Set start)
                this.fКолВыхПразд = value;
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолВыхПразд Set end)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолВыхПразд Set end)
            }
        }
        
        /// <summary>
        /// КолНеявок.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьТУ.КолНеявок CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьТУ.КолНеявок CustomAttributes)
        public virtual int КолНеявок
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолНеявок Get start)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолНеявок Get start)
                int result = this.fКолНеявок;
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолНеявок Get end)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолНеявок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолНеявок Set start)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолНеявок Set start)
                this.fКолНеявок = value;
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолНеявок Set end)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолНеявок Set end)
            }
        }
        
        /// <summary>
        /// КолЯвокМес.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьТУ.КолЯвокМес CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьТУ.КолЯвокМес CustomAttributes)
        public virtual int КолЯвокМес
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолЯвокМес Get start)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолЯвокМес Get start)
                int result = this.fКолЯвокМес;
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолЯвокМес Get end)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолЯвокМес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолЯвокМес Set start)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолЯвокМес Set start)
                this.fКолЯвокМес = value;
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолЯвокМес Set end)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолЯвокМес Set end)
            }
        }
        
        /// <summary>
        /// КолЯвокПМес.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьТУ.КолЯвокПМес CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьТУ.КолЯвокПМес CustomAttributes)
        public virtual int КолЯвокПМес
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолЯвокПМес Get start)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолЯвокПМес Get start)
                int result = this.fКолЯвокПМес;
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолЯвокПМес Get end)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолЯвокПМес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолЯвокПМес Set start)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолЯвокПМес Set start)
                this.fКолЯвокПМес = value;
                // *** Start programmer edit section *** (ТаблЧастьТУ.КолЯвокПМес Set end)

                // *** End programmer edit section *** (ТаблЧастьТУ.КолЯвокПМес Set end)
            }
        }
        
        /// <summary>
        /// КорресСчет.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьТУ.КорресСчет CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьТУ.КорресСчет CustomAttributes)
        public virtual int КорресСчет
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.КорресСчет Get start)

                // *** End programmer edit section *** (ТаблЧастьТУ.КорресСчет Get start)
                int result = this.fКорресСчет;
                // *** Start programmer edit section *** (ТаблЧастьТУ.КорресСчет Get end)

                // *** End programmer edit section *** (ТаблЧастьТУ.КорресСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.КорресСчет Set start)

                // *** End programmer edit section *** (ТаблЧастьТУ.КорресСчет Set start)
                this.fКорресСчет = value;
                // *** Start programmer edit section *** (ТаблЧастьТУ.КорресСчет Set end)

                // *** End programmer edit section *** (ТаблЧастьТУ.КорресСчет Set end)
            }
        }
        
        /// <summary>
        /// ЧасыЗаМесяц.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьТУ.ЧасыЗаМесяц CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьТУ.ЧасыЗаМесяц CustomAttributes)
        public virtual double ЧасыЗаМесяц
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.ЧасыЗаМесяц Get start)

                // *** End programmer edit section *** (ТаблЧастьТУ.ЧасыЗаМесяц Get start)
                double result = this.fЧасыЗаМесяц;
                // *** Start programmer edit section *** (ТаблЧастьТУ.ЧасыЗаМесяц Get end)

                // *** End programmer edit section *** (ТаблЧастьТУ.ЧасыЗаМесяц Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.ЧасыЗаМесяц Set start)

                // *** End programmer edit section *** (ТаблЧастьТУ.ЧасыЗаМесяц Set start)
                this.fЧасыЗаМесяц = value;
                // *** Start programmer edit section *** (ТаблЧастьТУ.ЧасыЗаМесяц Set end)

                // *** End programmer edit section *** (ТаблЧастьТУ.ЧасыЗаМесяц Set end)
            }
        }
        
        /// <summary>
        /// ЧасыЗаПМес.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьТУ.ЧасыЗаПМес CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьТУ.ЧасыЗаПМес CustomAttributes)
        public virtual double ЧасыЗаПМес
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.ЧасыЗаПМес Get start)

                // *** End programmer edit section *** (ТаблЧастьТУ.ЧасыЗаПМес Get start)
                double result = this.fЧасыЗаПМес;
                // *** Start programmer edit section *** (ТаблЧастьТУ.ЧасыЗаПМес Get end)

                // *** End programmer edit section *** (ТаблЧастьТУ.ЧасыЗаПМес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.ЧасыЗаПМес Set start)

                // *** End programmer edit section *** (ТаблЧастьТУ.ЧасыЗаПМес Set start)
                this.fЧасыЗаПМес = value;
                // *** Start programmer edit section *** (ТаблЧастьТУ.ЧасыЗаПМес Set end)

                // *** End programmer edit section *** (ТаблЧастьТУ.ЧасыЗаПМес Set end)
            }
        }
        
        /// <summary>
        /// ЯвкаНеявка.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧастьТУ.ЯвкаНеявка CustomAttributes)

        // *** End programmer edit section *** (ТаблЧастьТУ.ЯвкаНеявка CustomAttributes)
        public virtual bool ЯвкаНеявка
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.ЯвкаНеявка Get start)

                // *** End programmer edit section *** (ТаблЧастьТУ.ЯвкаНеявка Get start)
                bool result = this.fЯвкаНеявка;
                // *** Start programmer edit section *** (ТаблЧастьТУ.ЯвкаНеявка Get end)

                // *** End programmer edit section *** (ТаблЧастьТУ.ЯвкаНеявка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧастьТУ.ЯвкаНеявка Set start)

                // *** End programmer edit section *** (ТаблЧастьТУ.ЯвкаНеявка Set start)
                this.fЯвкаНеявка = value;
                // *** Start programmer edit section *** (ТаблЧастьТУ.ЯвкаНеявка Set end)

                // *** End programmer edit section *** (ТаблЧастьТУ.ЯвкаНеявка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТаблЧастьТУE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТаблЧастьТУE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТаблЧастьТУE", typeof(IIS.Otdel_kadrov_2.ТаблЧастьТУ));
                }
            }
            
            /// <summary>
            /// "ТаблЧастьТУL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТаблЧастьТУL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТаблЧастьТУL", typeof(IIS.Otdel_kadrov_2.ТаблЧастьТУ));
                }
            }
        }
    }
}
