//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel_kadrov_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Увольнение.
    /// </summary>
    // *** Start programmer edit section *** (Увольнение CustomAttributes)

    // *** End programmer edit section *** (Увольнение CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УвольнениеE", new string[] {
            "ДатаУвольнения as \'Дата увольнения\'",
            "ДатаДк as \'Дата дк\'",
            "Основание as \'Основание\'",
            "Ответственный as \'Ответственный\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "ОтделКадров as \'Отдел кадров\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("УвольнениеE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("УвольнениеE", "ОтделКадров", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [View("УвольнениеL", new string[] {
            "ДатаДк as \'Дата дк\'",
            "ДатаУвольнения as \'Дата увольнения\'",
            "Основание as \'Основание\'",
            "Ответственный as \'Ответственный\'",
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class Увольнение : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаУвольнения;
        
        private System.DateTime fДатаДк;
        
        private string fОснование;
        
        private string fОтветственный;
        
        private IIS.Otdel_kadrov_2.Сотрудники fСотрудники;
        
        private IIS.Otdel_kadrov_2.ОтделКадров fОтделКадров;
        
        // *** Start programmer edit section *** (Увольнение CustomMembers)

        // *** End programmer edit section *** (Увольнение CustomMembers)

        
        /// <summary>
        /// ДатаДк.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.ДатаДк CustomAttributes)

        // *** End programmer edit section *** (Увольнение.ДатаДк CustomAttributes)
        public virtual System.DateTime ДатаДк
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.ДатаДк Get start)

                // *** End programmer edit section *** (Увольнение.ДатаДк Get start)
                System.DateTime result = this.fДатаДк;
                // *** Start programmer edit section *** (Увольнение.ДатаДк Get end)

                // *** End programmer edit section *** (Увольнение.ДатаДк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.ДатаДк Set start)

                // *** End programmer edit section *** (Увольнение.ДатаДк Set start)
                this.fДатаДк = value;
                // *** Start programmer edit section *** (Увольнение.ДатаДк Set end)

                // *** End programmer edit section *** (Увольнение.ДатаДк Set end)
            }
        }
        
        /// <summary>
        /// ДатаУвольнения.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.ДатаУвольнения CustomAttributes)

        // *** End programmer edit section *** (Увольнение.ДатаУвольнения CustomAttributes)
        public virtual System.DateTime ДатаУвольнения
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.ДатаУвольнения Get start)

                // *** End programmer edit section *** (Увольнение.ДатаУвольнения Get start)
                System.DateTime result = this.fДатаУвольнения;
                // *** Start programmer edit section *** (Увольнение.ДатаУвольнения Get end)

                // *** End programmer edit section *** (Увольнение.ДатаУвольнения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.ДатаУвольнения Set start)

                // *** End programmer edit section *** (Увольнение.ДатаУвольнения Set start)
                this.fДатаУвольнения = value;
                // *** Start programmer edit section *** (Увольнение.ДатаУвольнения Set end)

                // *** End programmer edit section *** (Увольнение.ДатаУвольнения Set end)
            }
        }
        
        /// <summary>
        /// Основание.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.Основание CustomAttributes)

        // *** End programmer edit section *** (Увольнение.Основание CustomAttributes)
        [StrLen(255)]
        public virtual string Основание
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.Основание Get start)

                // *** End programmer edit section *** (Увольнение.Основание Get start)
                string result = this.fОснование;
                // *** Start programmer edit section *** (Увольнение.Основание Get end)

                // *** End programmer edit section *** (Увольнение.Основание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.Основание Set start)

                // *** End programmer edit section *** (Увольнение.Основание Set start)
                this.fОснование = value;
                // *** Start programmer edit section *** (Увольнение.Основание Set end)

                // *** End programmer edit section *** (Увольнение.Основание Set end)
            }
        }
        
        /// <summary>
        /// Ответственный.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.Ответственный CustomAttributes)

        // *** End programmer edit section *** (Увольнение.Ответственный CustomAttributes)
        [StrLen(255)]
        public virtual string Ответственный
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.Ответственный Get start)

                // *** End programmer edit section *** (Увольнение.Ответственный Get start)
                string result = this.fОтветственный;
                // *** Start programmer edit section *** (Увольнение.Ответственный Get end)

                // *** End programmer edit section *** (Увольнение.Ответственный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.Ответственный Set start)

                // *** End programmer edit section *** (Увольнение.Ответственный Set start)
                this.fОтветственный = value;
                // *** Start programmer edit section *** (Увольнение.Ответственный Set end)

                // *** End programmer edit section *** (Увольнение.Ответственный Set end)
            }
        }
        
        /// <summary>
        /// Увольнение.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.ОтделКадров CustomAttributes)

        // *** End programmer edit section *** (Увольнение.ОтделКадров CustomAttributes)
        [PropertyStorage(new string[] {
                "ОтделКадров"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov_2.ОтделКадров ОтделКадров
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.ОтделКадров Get start)

                // *** End programmer edit section *** (Увольнение.ОтделКадров Get start)
                IIS.Otdel_kadrov_2.ОтделКадров result = this.fОтделКадров;
                // *** Start programmer edit section *** (Увольнение.ОтделКадров Get end)

                // *** End programmer edit section *** (Увольнение.ОтделКадров Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.ОтделКадров Set start)

                // *** End programmer edit section *** (Увольнение.ОтделКадров Set start)
                this.fОтделКадров = value;
                // *** Start programmer edit section *** (Увольнение.ОтделКадров Set end)

                // *** End programmer edit section *** (Увольнение.ОтделКадров Set end)
            }
        }
        
        /// <summary>
        /// Увольнение.
        /// </summary>
        // *** Start programmer edit section *** (Увольнение.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Увольнение.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Otdel_kadrov_2.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Увольнение.Сотрудники Get start)

                // *** End programmer edit section *** (Увольнение.Сотрудники Get start)
                IIS.Otdel_kadrov_2.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Увольнение.Сотрудники Get end)

                // *** End programmer edit section *** (Увольнение.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Увольнение.Сотрудники Set start)

                // *** End programmer edit section *** (Увольнение.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Увольнение.Сотрудники Set end)

                // *** End programmer edit section *** (Увольнение.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УвольнениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УвольнениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УвольнениеE", typeof(IIS.Otdel_kadrov_2.Увольнение));
                }
            }
            
            /// <summary>
            /// "УвольнениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УвольнениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УвольнениеL", typeof(IIS.Otdel_kadrov_2.Увольнение));
                }
            }
        }
    }
}
